<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>None</DebugType>
    <DebugSymbols>False</DebugSymbols>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WatsonWebsocket" Version="4.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SheepQQBot3.Model\SheepQQBot3.Model.csproj" />
  </ItemGroup>

</Project>
