// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SheepQQBot3.DbModel.JiebaDb;

public partial class Dict
{
    public string Word { get; set; }

    public int Freq { get; set; }

    public string Tag { get; set; }

    public int IsDefault { get; set; }
}