// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SheepQQBot3.DbModel.JiebaDb;

public partial class Idf
{
    public string Word { get; set; }

    public decimal Weight { get; set; }
}