// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SheepQQBot3.DbModel.JiebaDb;

public partial class JiebaDbContext : DbContext
{
    public JiebaDbContext(DbContextOptions<JiebaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Dict> Dicts { get; set; }

    public virtual DbSet<Idf> Idfs { get; set; }

    public virtual DbSet<StopWord> StopWords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Dict>(entity =>
        {
            entity.HasKey(e => e.Word);

            entity.ToTable("Dict");

            entity.Property(e => e.Word).HasDefaultValue("");
            entity.Property(e => e.Freq).HasDefaultValue(1);
            entity.Property(e => e.Tag)
                .IsRequired()
                .HasDefaultValue("");
        });

        modelBuilder.Entity<Idf>(entity =>
        {
            entity.HasKey(e => e.Word);

            entity.ToTable("Idf");

            entity.Property(e => e.Word).HasDefaultValue("");
            entity.Property(e => e.Weight)
                .HasDefaultValueSql("0")
                .HasColumnType("NUMBER");
        });

        modelBuilder.Entity<StopWord>(entity =>
        {
            entity.HasKey(e => e.Word);

            entity.Property(e => e.Word).HasDefaultValue("");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}