// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SheepQQBot3.DBModel
{
    public partial class BotDbContext : DbContext
    {
        public BotDbContext()
        {
        }

        public BotDbContext(DbContextOptions<BotDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SetuDoushiInfo>(entity =>
            {
                entity.HasKey(e => e.TargetId);

                entity.Property(e => e.TargetId).ValueGeneratedNever();
            });

            modelBuilder.Entity<SetuSendHistory>(entity =>
            {
                entity.HasKey(e => new { e.TargetId, e.TimeStamp });
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}