// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SheepQQBot3.DbModel;

public partial class BotDbContext : DbContext
{
    public BotDbContext(DbContextOptions<BotDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BotGroupMessage>(entity =>
        {
            entity.HasKey(e => new { e.GroupId, e.TargetId, e.MessageId, e.TimeStamp });

            entity.ToTable("BotGroupMessage");
        });

        modelBuilder.Entity<SetuDoushiInfo>(entity =>
        {
            entity.HasKey(e => e.TargetId);

            entity.HasIndex(e => e.TargetId, "KEY_TargetId").IsUnique();

            entity.Property(e => e.TargetId).ValueGeneratedNever();
        });

        modelBuilder.Entity<SetuSendHistory>(entity =>
        {
            entity.HasKey(e => new { e.TargetId, e.TimeStamp });

            entity.Property(e => e.SearchKeyword)
                .IsRequired()
                .HasDefaultValueSql("搜索");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}