<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>None</DebugType>
    <DebugSymbols>False</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google_GenerativeAI" Version="3.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\SheepQQBot3.Model\SheepQQBot3.Model.csproj" />
    <ProjectReference Include="..\SheepQQBot3.SDK.Server\SheepQQBot3.SDK.Server.csproj" />
    <ProjectReference Include="..\SheepQQBot3\SheepQQBot3.csproj" />
  </ItemGroup>

</Project>
