// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace SheepQQBot3.DbModel;

public partial class BotDbContext
{
    public bool _autoSaveOnDispose = false;

    public override async ValueTask DisposeAsync()
    {
        if (_autoSaveOnDispose && ChangeTracker.HasChanges())
        {
            try
            {
                await SaveChangesAsync();
            }
            catch (Exception ex)
            {
                // 这里要非常小心，如果保存失败，可能会掩盖掉原本的业务异常
                // 建议至少打个日志
                Console.WriteLine($"自动保存失败: {ex.Message}");
            }
        }

        await base.DisposeAsync();
    }

    /// <inheritdoc />
    public override ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = new CancellationToken())
    {
        _autoSaveOnDispose = true;
        return base.AddAsync(entity, cancellationToken);
    }

    /// <inheritdoc />
    public override ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = new CancellationToken())
    {
        _autoSaveOnDispose = true;
        return base.AddAsync(entity, cancellationToken);
    }

    /// <inheritdoc />
    public override EntityEntry<TEntity> Update<TEntity>(TEntity entity)
    {
        _autoSaveOnDispose = true;
        return base.Update(entity);
    }

    /// <inheritdoc />
    public override EntityEntry Update(object entity)
    {
        _autoSaveOnDispose = true;
        return base.Update(entity);
    }

    /// <inheritdoc />
    public override EntityEntry<TEntity> Add<TEntity>(TEntity entity)
    {
        _autoSaveOnDispose = true;
        return base.Add(entity);
    }

    /// <inheritdoc />
    public override EntityEntry Add(object entity)
    {
        _autoSaveOnDispose = true;
        return base.Add(entity);
    }

    /// <inheritdoc />
    public override EntityEntry<TEntity> Remove<TEntity>(TEntity entity)
    {
        _autoSaveOnDispose = true;
        return base.Remove(entity);
    }

    /// <inheritdoc />
    public override EntityEntry Remove(object entity)
    {
        _autoSaveOnDispose = true;
        return base.Remove(entity);
    }
}