// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SheepQQBot3.DbModel;

public partial class BotGroupMessage
{
    public string GroupId { get; set; }

    public string TargetId { get; set; }

    public string MessageId { get; set; }

    public long TimeStamp { get; set; }

    public string MessageText { get; set; }
}