// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SheepQQBot3.DbModel;

public partial class SetuDoushiInfo
{
    public string TargetId { get; set; }

    public long SetuDoushiLv { get; set; }

    public long ToFastTimes { get; set; }

    public long SetuCD { get; set; }

    public long BlackListCD { get; set; }
}